import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { SEMANTIC_ANNOTATION_DEFINITIONS, SYSTEM_SLOT_DEFINITIONS } from '@netior/shared/constants';
import type { SlotSemanticAnnotationKey, SystemSlotKey } from '@netior/shared/types';
import {
  createArchetypeField,
  deleteArchetypeField,
  listArchetypeFields,
  reorderArchetypeFields,
  updateArchetypeField,
} from '../netior-service-client.js';
import { emitChange } from '../events.js';
import { registerNetiorTool } from './shared-tool-registry.js';

const fieldTypeSchema = z.enum([
  'text',
  'textarea',
  'number',
  'boolean',
  'date',
  'datetime',
  'select',
  'multi-select',
  'radio',
  'relation',
  'file',
  'url',
  'color',
  'rating',
  'tags',
  'archetype_ref',
]);

const systemSlotKeys = new Set(SYSTEM_SLOT_DEFINITIONS.map((definition) => definition.key));
const systemSlotSchema = z.string().refine(
  (value) => systemSlotKeys.has(value as never),
  'Invalid system slot key',
);
const slotAnnotationKeys = new Set(
  SEMANTIC_ANNOTATION_DEFINITIONS
    .filter((definition) => definition.scope === 'slot')
    .map((definition) => definition.key),
);
const slotSemanticAnnotationSchema = z.string().refine(
  (value) => slotAnnotationKeys.has(value as never),
  'Invalid slot semantic annotation key',
);

export function registerArchetypeFieldTools(server: McpServer): void {
  registerNetiorTool(
    server,
    'list_archetype_fields',
    { archetype_id: z.string().describe('The schema ID') },
    async ({ archetype_id }) => {
      try {
        const result = await listArchetypeFields(archetype_id);
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'create_archetype_field',
    {
      archetype_id: z.string().describe('The schema ID'),
      name: z.string().describe('Slot name'),
      field_type: fieldTypeSchema.describe('Slot value type'),
      sort_order: z.number().describe('Slot order index'),
      required: z.boolean().optional().describe('Whether the slot is required'),
      default_value: z.string().optional().describe('Default value'),
      options: z.string().optional().describe('Comma-separated inline options for select-like fields'),
      ref_archetype_id: z.string().optional().describe('Referenced schema ID for archetype_ref slots'),
      semantic_annotation: slotSemanticAnnotationSchema.nullable().optional().describe('Optional slot semantic annotation or null'),
      system_slot: systemSlotSchema.nullable().optional().describe('Legacy optional system slot key or null'),
      slot_binding_locked: z.boolean().optional().describe('Whether the semantic annotation binding is locked'),
      generated_by_trait: z.boolean().optional().describe('Whether this slot was generated by a schema facet'),
    },
    async ({
      archetype_id,
      name,
      field_type,
      sort_order,
      required,
      default_value,
      options,
      ref_archetype_id,
      semantic_annotation,
      system_slot,
      slot_binding_locked,
      generated_by_trait,
    }) => {
      try {
        const result = await createArchetypeField({
          archetype_id,
          name,
          field_type,
          sort_order,
          required,
          default_value,
          options,
          ref_archetype_id,
          semantic_annotation: semantic_annotation as SlotSemanticAnnotationKey | null | undefined,
          system_slot: system_slot as SystemSlotKey | null | undefined,
          slot_binding_locked,
          generated_by_trait,
        });
        emitChange({ type: 'archetypeField', action: 'create', id: result.id });
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'update_archetype_field',
    {
      field_id: z.string().describe('The slot ID to update'),
      name: z.string().optional().describe('New slot name'),
      field_type: fieldTypeSchema.optional().describe('New slot value type'),
      sort_order: z.number().optional().describe('New slot order index'),
      required: z.boolean().optional().describe('Whether the slot is required'),
      default_value: z.string().nullable().optional().describe('New default value'),
      options: z.string().nullable().optional().describe('New comma-separated inline options'),
      ref_archetype_id: z.string().nullable().optional().describe('Referenced schema ID or null'),
      semantic_annotation: slotSemanticAnnotationSchema.nullable().optional().describe('New slot semantic annotation or null'),
      system_slot: systemSlotSchema.nullable().optional().describe('Legacy new system slot key or null'),
      slot_binding_locked: z.boolean().optional().describe('Whether the semantic annotation binding is locked'),
      generated_by_trait: z.boolean().optional().describe('Whether this slot was generated by a schema facet'),
    },
    async ({
      field_id,
      name,
      field_type,
      sort_order,
      required,
      default_value,
      options,
      ref_archetype_id,
      semantic_annotation,
      system_slot,
      slot_binding_locked,
      generated_by_trait,
    }) => {
      try {
        const result = await updateArchetypeField(field_id, {
          name,
          field_type,
          sort_order,
          required,
          default_value,
          options,
          ref_archetype_id,
          semantic_annotation: semantic_annotation as SlotSemanticAnnotationKey | null | undefined,
          system_slot: system_slot as SystemSlotKey | null | undefined,
          slot_binding_locked,
          generated_by_trait,
        });
        if (!result) {
          return {
            content: [{ type: 'text' as const, text: `Error: Schema slot not found: ${field_id}` }],
            isError: true,
          };
        }
        emitChange({ type: 'archetypeField', action: 'update', id: field_id });
        return {
          content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'delete_archetype_field',
    { field_id: z.string().describe('The slot ID to delete') },
    async ({ field_id }) => {
      try {
        const deleted = await deleteArchetypeField(field_id);
        if (!deleted) {
          return {
            content: [{ type: 'text' as const, text: `Error: Schema slot not found: ${field_id}` }],
            isError: true,
          };
        }
        emitChange({ type: 'archetypeField', action: 'delete', id: field_id });
        return {
          content: [{ type: 'text' as const, text: JSON.stringify({ success: true, id: field_id }) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );

  registerNetiorTool(
    server,
    'reorder_archetype_fields',
    {
      archetype_id: z.string().describe('The schema ID'),
      ordered_ids: z.array(z.string()).describe('Slot IDs in the desired order'),
    },
    async ({ archetype_id, ordered_ids }) => {
      try {
        const success = await reorderArchetypeFields(archetype_id, ordered_ids);
        return {
          content: [{ type: 'text' as const, text: JSON.stringify({ success, archetype_id, ordered_ids }, null, 2) }],
        };
      } catch (error) {
        return {
          content: [{ type: 'text' as const, text: `Error: ${(error as Error).message}` }],
          isError: true,
        };
      }
    },
  );
}
