import type { ShortcutDefinition } from './shortcut-types';

export const SHORTCUT_REGISTRY: ShortcutDefinition[] = [
  {
    id: 'shortcut.global.saveActiveTab',
    description: 'Save the active tab',
    keybinding: 'Ctrl/Cmd+S',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.closeActiveTab',
    description: 'Close the active tab',
    keybinding: 'Ctrl/Cmd+W',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openSettings',
    description: 'Open settings',
    keybinding: 'Ctrl/Cmd+,',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openShortcutOverlay',
    description: 'Open the keyboard shortcuts overlay',
    keybinding: 'Ctrl/Cmd+/',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.toggleSidebar',
    description: 'Toggle the sidebar',
    keybinding: 'Ctrl/Cmd+B',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openTerminal',
    description: 'Open a new terminal tab',
    keybinding: 'Ctrl/Cmd+Shift+N',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openNarre',
    description: 'Open the Narre tab for the current project',
    keybinding: 'Ctrl/Cmd+Alt+N',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
    when: 'A project is open',
  },
  {
    id: 'shortcut.global.nextTab',
    description: 'Activate the next tab',
    keybinding: 'Ctrl/Cmd+Tab',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.previousTab',
    description: 'Activate the previous tab',
    keybinding: 'Ctrl/Cmd+Shift+Tab',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.global.openTabByIndex',
    description: 'Activate a tab by index; 9 opens the last tab',
    keybinding: 'Ctrl/Cmd+1..9',
    scope: 'global',
    owner: 'globalDispatcher',
    priority: 'global',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.openSelection',
    description: 'Open the selected file or toggle the selected directory',
    keybinding: 'Enter',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.renameSelection',
    description: 'Rename the selected file-tree item',
    keybinding: 'F2',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.deleteSelection',
    description: 'Delete the selected file-tree item',
    keybinding: 'Delete',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.copySelection',
    description: 'Copy the selected file-tree item',
    keybinding: 'Ctrl/Cmd+C',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.cutSelection',
    description: 'Cut the selected file-tree item',
    keybinding: 'Ctrl/Cmd+X',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.fileTree.pasteIntoSelection',
    description: 'Paste into the selected directory or the parent of the selected file',
    keybinding: 'Ctrl/Cmd+V',
    scope: 'fileTree',
    owner: 'fileTree',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.canvas.selectAllNodes',
    description: 'Select all nodes in the active canvas',
    keybinding: 'Ctrl/Cmd+A',
    scope: 'canvas',
    owner: 'canvasContext',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.canvas.deleteSelection',
    description: 'Delete selected nodes in the active canvas',
    keybinding: 'Delete',
    scope: 'canvas',
    owner: 'canvasContext',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.canvas.cancelLinking',
    description: 'Cancel edge linking in the active canvas',
    keybinding: 'Escape',
    scope: 'canvas',
    owner: 'canvasContext',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.canvas.toggleMode',
    description: 'Toggle canvas browse/edit mode',
    keybinding: 'E',
    scope: 'canvas',
    owner: 'canvasContext',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.canvas.fitToScreen',
    description: 'Fit the active canvas content to the viewport',
    keybinding: 'F',
    scope: 'canvas',
    owner: 'canvasContext',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.openSearch',
    description: 'Open terminal search',
    keybinding: 'Ctrl/Cmd+F',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.copySelection',
    description: 'Copy the current terminal selection',
    keybinding: 'Ctrl/Cmd+C',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
    when: 'Selection exists',
  },
  {
    id: 'shortcut.terminal.paste',
    description: 'Paste into terminal',
    keybinding: 'Ctrl/Cmd+V',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.fontSizeUp',
    description: 'Increase terminal font size',
    keybinding: 'Ctrl/Cmd+=',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.fontSizeDown',
    description: 'Decrease terminal font size',
    keybinding: 'Ctrl/Cmd+-',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.fontSizeReset',
    description: 'Reset terminal font size',
    keybinding: 'Ctrl/Cmd+0',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.pageScrollUp',
    description: 'Scroll the terminal one page up',
    keybinding: 'Shift+PageUp',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.terminal.pageScrollDown',
    description: 'Scroll the terminal one page down',
    keybinding: 'Shift+PageDown',
    scope: 'terminal',
    owner: 'terminalEditor',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.narreChat.sendMessage',
    description: 'Send the current Narre message',
    keybinding: 'Enter',
    scope: 'narreChat',
    owner: 'narreChat',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.narreChat.insertNewline',
    description: 'Insert a newline in Narre input',
    keybinding: 'Shift+Enter',
    scope: 'narreChat',
    owner: 'narreChat',
    priority: 'context',
    implemented: true,
  },
  {
    id: 'shortcut.narreMentionPicker.selectNext',
    description: 'Move to the next Narre mention result',
    keybinding: 'ArrowDown',
    scope: 'narreMentionPicker',
    owner: 'narreMentionPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreMentionPicker.selectPrevious',
    description: 'Move to the previous Narre mention result',
    keybinding: 'ArrowUp',
    scope: 'narreMentionPicker',
    owner: 'narreMentionPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreMentionPicker.confirmSelection',
    description: 'Insert the selected Narre mention',
    keybinding: 'Enter',
    scope: 'narreMentionPicker',
    owner: 'narreMentionPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreMentionPicker.close',
    description: 'Close the Narre mention picker',
    keybinding: 'Escape',
    scope: 'narreMentionPicker',
    owner: 'narreMentionPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreSlashPicker.selectNext',
    description: 'Move to the next Narre slash command',
    keybinding: 'ArrowDown',
    scope: 'narreSlashPicker',
    owner: 'narreSlashPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreSlashPicker.selectPrevious',
    description: 'Move to the previous Narre slash command',
    keybinding: 'ArrowUp',
    scope: 'narreSlashPicker',
    owner: 'narreSlashPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreSlashPicker.confirmSelection',
    description: 'Insert the selected Narre slash command',
    keybinding: 'Enter',
    scope: 'narreSlashPicker',
    owner: 'narreSlashPicker',
    priority: 'local',
    implemented: true,
  },
  {
    id: 'shortcut.narreSlashPicker.close',
    description: 'Close the Narre slash picker',
    keybinding: 'Escape',
    scope: 'narreSlashPicker',
    owner: 'narreSlashPicker',
    priority: 'local',
    implemented: true,
  },
];

export function getShortcutDefinition(id: string): ShortcutDefinition | undefined {
  return SHORTCUT_REGISTRY.find((shortcut) => shortcut.id === id);
}
